#ifndef __RADAR_H
#define __RADAR_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>



#define XENSIV_BGT60TRXX_CONF_DEVICE (XENSIV_DEVICE_BGT60UTR11AIP)
#define XENSIV_BGT60TRXX_CONF_START_FREQ_HZ (57400001000)
#define XENSIV_BGT60TRXX_CONF_END_FREQ_HZ (62999998000)
#define XENSIV_BGT60TRXX_CONF_NUM_SAMPLES_PER_CHIRP (512)
#define XENSIV_BGT60TRXX_CONF_NUM_CHIRPS_PER_FRAME (8)
#define XENSIV_BGT60TRXX_CONF_NUM_RX_ANTENNAS (1)
#define XENSIV_BGT60TRXX_CONF_NUM_TX_ANTENNAS (1)
#define XENSIV_BGT60TRXX_CONF_SAMPLE_RATE (1000000)
#define XENSIV_BGT60TRXX_CONF_CHIRP_REPETITION_TIME_S (0.00419988)
#define XENSIV_BGT60TRXX_CONF_FRAME_REPETITION_TIME_S (0.0799223)
#define XENSIV_BGT60TRXX_CONF_NUM_REGS (40)

#define NUM_SAMPLES_PER_FRAME               (XENSIV_BGT60TRXX_CONF_NUM_RX_ANTENNAS *\
                                             XENSIV_BGT60TRXX_CONF_NUM_CHIRPS_PER_FRAME *\
                                             XENSIV_BGT60TRXX_CONF_NUM_SAMPLES_PER_CHIRP)

void radar_setup();
void radar_loop();
void radar_irq();

#ifdef __cplusplus
}
#endif

#endif